kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-two
networking:
  apiServerPort: 19092
  apiServerAddress: 172.31.12.41
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 38080
    hostPort: 8080
  - containerPort: 36443
    hostPort: 6443
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
- role: worker
