kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-one
networking:
  apiServerPort: 19091
  apiServerAddress: 172.31.12.41
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
  - containerPort: 30443
    hostPort: 443
  extraMounts:
  - hostPath: /var/run/docker.sock
    containerPath: /var/run/docker.sock
