apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex
  namespace: monitoring
data:
  cortex.yaml: |-
    api:
      prometheus_http_prefix: /prometheus
      response_compression_enabled: true
    auth_enabled: false
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data
      s3:
        access_key_id: admin
        bucket_name: monitoring
        endpoint: 172.31.14.138:9000
        insecure: true
        secret_access_key: admin2675
      tsdb:
        dir: /data
    chunk_store:
      chunk_cache_config:
        memcached:
          expiration: 1h
        memcached_client:
          timeout: 1s
    distributor:
      pool:
        health_check_ingesters: true
      shard_by_all_labels: true
    frontend:
      log_queries_longer_than: 10s
    ingester:
      lifecycler:
        final_sleep: 0s
        join_after: 0s
        num_tokens: 512
        ring:
          kvstore:
            consul:
              consistent_reads: true
              host: consul:8500
              http_client_timeout: 20s
            prefix: collectors/
            store: consul
          replication_factor: 3
      max_transfer_retries: 0
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      enforce_metric_name: false
      max_query_lookback: 0s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    memberlist:
      bind_port: 7946
      join_members: []
    querier:
      active_query_tracker_dir: /data/cortex/querier
      query_ingesters_within: 12h
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          memcached:
            expiration: 1h
          memcached_client:
            timeout: 1s
      split_queries_by_interval: 24h
    # https://github.com/cortexproject/cortex/issues/3401#issuecomment-864033508      
    ruler:
      alertmanager_url: http://alertmanager:9093/
      enable_alertmanager_discovery: false
      enable_alertmanager_v2: true
      enable_api: true
      external_url: https://alerts.example.org/
      rule_path: /rules
      storage:
        local:
          directory: /etc/cortex/rules/fake
        type: local
    schema:
      configs:
      - from: "2020-11-01"
        index:
          period: 168h
          prefix: index_
        object_store: s3
        schema: v10
        store: aws-dynamo
    server:
      grpc_listen_port: 9095
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      http_listen_port: 8080
    storage:
      aws:
        dynamodb:
          api_limit: null
          chunk_gang_size: null
          chunk_get_max_parallelism: null
          dynamodb_url: dynamodb://user:pass@dynamodb.monitoring.svc.cluster.local:8000
          metrics:
            ignore_throttle_below: null
            queue_length_query: null
            read_error_query: null
            read_usage_query: null
            scale_up_factor: null
            target_queue_length: 10
            url: null
            write_throttle_query: null
            write_usage_query: null
          throttle_limit: null
      engine: chunks
      index_queries_cache_config:
        memcached:
          expiration: 1
        memcached_client:
          timeout: 1s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
