{
 "title": "⭐️ Kubernetes PoD Monitoring",
 "description": "Kubernetes PoD monitoring using prometheus.",
 "tags": [ "Kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node)" } },
   { "name": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Project",
    "query": {
     "query": "label_values(kube_namespace_status_phase{cluster=\"$Cluster\"},namespace)"
    }
   },
   {
    "name": "PoD",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$Cluster\",namespace=\"$Project\"},pod)"
    }
   },
   {
    "name": "PoD_Node",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$Cluster\",namespace=\"$Project\",pod=\"$PoD\"},node)"
    }
   },
   { "name": "Log_Cluster", "query": "label_values(cluster)" },
   {
    "name": "Log_Project",
    "query": "label_values({cluster=\"$Cluster\"},namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{cluster=\"$Cluster\",job=\"node-exporter\",mode=\"idle\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{cluster=\"$Cluster\"}) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes{cluster=\"$Cluster\"}) ) / sum(node_memory_MemTotal_bytes{cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk-1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{cluster=\"$Cluster\",device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{cluster=\"$Cluster\",device=~\"/dev/.*\"}) ) / sum(node_filesystem_size_bytes{cluster=\"$Cluster\",device=~\"/dev/.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Kubernetes Core Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg by (job) (up{job=~\"kubelet|apiserver\"}))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sort(avg by (container)  (kube_pod_container_status_running{container=~\"kube-controller-manager|kube-scheduler|etcd|coredns\",namespace=\"kube-system\"}))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "PoD Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{cluster=\"$Cluster\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Container Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=\"$Cluster\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD Capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{cluster=\"$Cluster\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_condition{condition=\"Ready\",job=\"kube-state-metrics\",status=\"true\",cluster=\"$Cluster\"} == 1)",
     "legendFormat": "Running "
    }
   ]
  },
  { "title": "PoD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pods Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sort_desc (sum (container_memory_usage_bytes{cluster=\"$Cluster\",image!=\"\",pod=\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}) by (pod,node))",
     "legendFormat": "{{ pod }}  ({{ node }}  )"
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=\"$Cluster\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod,node)",
     "legendFormat": "{{ pod }}  ({{ node }}  )"
    }
   ]
  },
  {
   "title": "Pods logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{cluster=\"$Cluster\",instance=~\"$PoD\",namespace=~\"^$Project$\"} "
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{cluster=\"$Cluster\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod)",
     "legendFormat": "IN"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod)",
     "legendFormat": "OUT"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Node CPU ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{cluster=\"$Cluster\",job=\"node-exporter\",mode=\"idle\",instance=~\"$PoD_Node\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) - ((node_memory_MemFree_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Buffers_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Cached_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}))) / (node_memory_MemTotal_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Disk1",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes {cluster=\"$Cluster\",job=\"node-exporter\",device=~\"/dev/.*\",instance=~\"$PoD_Node\",mountpoint=\"/etc/hosts\"}) - (node_filesystem_free_bytes {cluster=\"$Cluster\",job=\"node-exporter\",device=~\"/dev/.*\",instance=~\"$PoD_Node\",mountpoint=\"/etc/hosts\"})) / (node_filesystem_size_bytes {cluster=\"$Cluster\",job=\"node-exporter\",device=~\"/dev/.*\",instance=~\"$PoD_Node\",mountpoint=\"/etc/hosts\"}\r\n) * 100"
    }
   ]
  },
  {
   "title": "Node Name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 25 },
   "options": { "content": "    $PoD_Node\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=\"$Cluster\",instance=\"$PoD_Node\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kubelet_running_pods{cluster=\"$Cluster\",instance=\"$PoD_Node\"} ",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "PoD Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 25 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_pods{cluster=\"$Cluster\",node=\"$PoD_Node\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_cpu_seconds_total{cluster=\"$Cluster\",instance=\"$PoD_Node\"}[10m]))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Node Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) - ((node_memory_MemFree_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Buffers_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Cached_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}))",
     "legendFormat": "usage"
    },
    {
     "expr": "(node_memory_Buffers_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "buffers"
    },
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "(node_memory_MemFree_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "free"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$PoD_Node\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Node load usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(node_load1{cluster=\"$Cluster\",instance=\"$PoD_Node\"})",
     "legendFormat": "Load 1"
    },
    {
     "expr": "sum(node_load5{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 5"
    },
    {
     "expr": "sum(node_load15{instance=\"$PoD_Node\"})",
     "legendFormat": "Load 15"
    }
   ]
  },
  {
   "title": "Node Disk usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$Cluster\",instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "Write"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=\"$PoD_Node\"}[5m])) ",
     "legendFormat": "IO time"
    }
   ]
  },
  {
   "title": "Node Network usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "sum (rate(node_network_transmit_bytes_total{cluster=\"$Cluster\",instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "node_out"
    },
    {
     "expr": "sum (rate (node_network_transmit_bytes_total{device=\"eth0\",instance=\"$PoD_Node\"}[5m]))",
     "legendFormat": "eth0 out"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{pod=~\"$PoD\"}",
       "legendFormat": "current  "
      },
      {
       "expr": "jvm_threads_daemon{pod=~\"$PoD\"}",
       "legendFormat": "daemon "
      },
      {
       "expr": "jvm_threads_deadlocked {pod=~\"$PoD\"}",
       "legendFormat": "deadlock"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor {pod=~\"$PoD\"}",
       "legendFormat": "deadlock monitor"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{pod=~\"$PoD\"}",
       "legendFormat": "{{area}} memory "
      }
     ]
    },
    {
     "title": "GC time / 1 min. rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$PoD\"}[1m])",
       "legendFormat": "{{gc}} "
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{pod=~\"$PoD\"}",
       "legendFormat": "{{gc}} "
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{pod=~\"$PoD\"}",
       "legendFormat": "loaded "
      }
     ]
    }
   ]
  },
  {
   "title": "MQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages in Queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages{instance=~\"$PoD\",queue!=\"\"}",
       "legendFormat": "Queue ( {{queue}} )"
      }
     ]
    }
   ]
  }
 ]
}