{
 "title": "?? Multiple Kubernetes Cluster Monitoring",
 "description": " Multiple Kubernetes Monitoring using Prometheus.",
 "tags": [
  "Kubernetes",
  "Multi-cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Node", "query": { "query": "label_values(node)" } },
   { "name": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "Project",
    "query": {
     "query": "label_values({cluster=\"$Cluster\"},namespace)"
    }
   },
   {
    "name": "PoD",
    "query": {
     "query": "label_values({cluster=\"$Cluster\",namespace=\"$Project\"},pod)"
    }
   },
   {
    "name": "PoD_Node",
    "query": {
     "query": "label_values({cluster=\"$Cluster\",namespace=\"$Project\",pod=\"$PoD\"},instance)"
    }
   },
   { "name": "Log_Cluster", "query": "label_values(cluster)" },
   {
    "name": "Log_Project",
    "query": "label_values({cluster=\"$Log_Cluster\"},namespace)"
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values({cluster=\"$Cluster\"}, controller_namespace)"
    }
   },
   {
    "name": "controller_class",
    "query": {
     "query": "label_values({cluster=\"$Cluster\",controller_namespace=\"$namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values({cluster=~\"$Cluster\",controller_namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{cluster=~\"$Cluster\",controller_namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller_pod=~\"$controller\",namespace=\"$Project\"}, ingress) "
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(\n   count(irate(container_cpu_usage_seconds_total{id=\"/\",cluster=\"$Cluster\"}[10m])) by (instance)\n   * on (instance) \n   sum(irate(container_cpu_usage_seconds_total{id=\"/\",cluster=\"$Cluster\"}[10m])) by (instance)\n ) \n / \n (sum (kube_node_status_allocatable{resource=\"cpu\", unit=\"core\",cluster=\"$Cluster\"}))\n) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(container_memory_usage_bytes{namespace!=\"\",cluster=\"$Cluster\"}) / SUM(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"memory\", unit=\"byte\",cluster=\"$Cluster\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk-1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{cluster=\"$Cluster\",device=~\"/dev/.*\"}) - sum(node_filesystem_free_bytes{cluster=\"$Cluster\",device=~\"/dev/.*\"}) ) / sum(node_filesystem_size_bytes{cluster=\"$Cluster\",device=~\"/dev/.*\"}) * 100"
    }
   ]
  },
  {
   "title": "Kubernetes Core Services",
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(avg by (job) (up{job=~\"kubelet|apiserver\"}))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sort(avg by (container)  (kube_pod_container_status_running{container=~\"kube-controller-manager|kube-scheduler|etcd|coredns\",namespace=\"kube-system\"}))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "PODs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{cluster=\"$Cluster\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{cluster=\"$Cluster\"})",
     "legendFormat": "Running "
    }
   ]
  },
  {
   "title": "Nodes ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Namespaces ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " count(kube_namespace_created)", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "PVCs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ReadOnly PVC",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_spec_volumes_persistentvolumeclaims_readonly != 0) "
    }
   ]
  },
  {
   "title": "Cluster  node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_node_status_condition{job=\"kube-state-metrics\",status=\"true\",condition=\"Ready\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cluster age",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - kube_service_created{namespace=\"default\",service=\"kubernetes\"})"
    }
   ]
  },
  {
   "title": "Waiting pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_waiting !=0 )"
    }
   ]
  },
  {
   "title": "Terminated pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_terminated_reason{reason!=\"Completed\"} !=0 ) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Burstable  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.burstable.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Besteffort  pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(container_spec_memory_reservation_limit_bytes{id=~\".*.besteffort.*\",id!~\".*.scope\",pod!=\"\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Waiting/Terminated pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(namespace,reason,pod) (kube_pod_container_status_terminated_reason {reason!=\"Completed\"} !=0 )",
     "legendFormat": "TERMINATED::{{reason}}::{{pod}}( {{namespace}} )"
    },
    {
     "expr": "count(kube_pod_container_status_waiting !=0 ) by (namespace,pod,reason) ",
     "legendFormat": "WAITING::{{reason}}::{{pod}}( {{namespace}} )"
    },
    {}
   ]
  },
  {
   "title": "cluster  node details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{node}}" },
    {
     "expr": "((label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))  -  (label_replace((node_memory_MemAvailable_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\"))) /  (label_replace((node_memory_MemTotal_bytes  + on(instance) group_left(nodename) \nnode_uname_info),\"node\",\"$1\",\"nodename\", \"(.+)\")) "
    },
    {
     "expr": "max\n  by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"})\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\n"
    },
    {
     "expr": "sum by (node)(label_replace(instance:node_cpu:ratio + on(instance) group_left(nodename) \nnode_uname_info,\"node\",\"$1\",\"nodename\", \"(.+)\") ) / sum by (node)(kube_node_status_capacity{resource=\"cpu\"})"
    },
    { "expr": "kube_node_role" }
   ]
  },
  {
   "title": "Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization by Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\",pod!=\"\"}[10m]))  by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory Utilization by Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container!=\"POD\",container!=\"\"}) by (namespace) / 1024/1024/1024",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "CPU Request by Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "CPU Limit by Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory Requested by Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace) / 1024/1024/1024",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Memory Limit by Namespace",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace) / 1024/1024/1024",
       "legendFormat": "{{ namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "PoD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sort_desc (sum (container_memory_usage_bytes{cluster=\"$Cluster\",image!=\"\",pod=\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}) by (pod,node))",
       "legendFormat": "{{ pod }}  ({{ node }}  )"
      }
     ]
    },
    {
     "title": "Pods CPU usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=\"$Cluster\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod,node)",
       "legendFormat": "{{ pod }}  ({{ node }}  )"
      }
     ]
    },
    {
     "title": "Pods logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{pod=\"$PoD\",namespace=\"$Project\",cluster=\"$Cluster\"}"
      }
     ]
    },
    {
     "title": "Ingress Request Volume",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_requests{cluster=~\"$Cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",namespace=\"$Project\"}[2m])) by (ingress), 0.001)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Ingress Success Rate (non-4|5xx responses)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{cluster=~\"$Cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",namespace=\"$Project\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{cluster=~\"$Cluster\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",namespace=\"$Project\"}[2m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Pods network I/O",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{cluster=\"$Cluster\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod)",
       "legendFormat": "IN"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"$PoD\",namespace=~\"^$Project$\",node=~\"^$Node$\"}[2m])) by (pod)",
       "legendFormat": "OUT"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{cluster=\"$Cluster\",job=\"node-exporter\",mode=\"idle\",instance=~\"$PoD_Node\"}[5m])) * 100))"
      }
     ]
    },
    {
     "title": "Node Memory",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) - ((node_memory_MemFree_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Buffers_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Cached_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}))) / (node_memory_MemTotal_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) * 100"
      }
     ]
    },
    {
     "title": "Node Disk1",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes {cluster=\"$Cluster\",job=\"node-exporter\",device=~\"/dev/.*\",instance=~\"$PoD_Node\",mountpoint=\"/\"}) - (node_filesystem_free_bytes {cluster=\"$Cluster\",job=\"node-exporter\",device=~\"/dev/.*\",instance=~\"$PoD_Node\",mountpoint=\"/\"})) / (node_filesystem_size_bytes {cluster=\"$Cluster\",job=\"node-exporter\",device=~\"/dev/.*\",instance=~\"$PoD_Node\",mountpoint=\"/\"}\n) * 100"
      }
     ]
    },
    {
     "title": "Node Name",
     "type": "text",
     "gridPos": { "h": 5, "w": 4, "x": 9, "y": 4 },
     "options": { "content": "      $PoD_Node\n\n" },
     "targets": [
      {}
     ]
    },
    {
     "title": "Node Role",
     "type": "table",
     "gridPos": { "h": 5, "w": 3, "x": 13, "y": 4 },
     "targets": [
      {
       "expr": "kube_node_role{node=\"$PoD_Node\"}"
      }
     ]
    },
    {
     "title": "Container ",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kubelet_running_containers{cluster=\"$Cluster\",instance=\"$PoD_Node\"})",
       "legendFormat": "Running "
      }
     ]
    },
    {
     "title": "Memory/Disk/PID/Network Pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kube_node_status_condition{cluster=\"$Cluster\",node=\"$PoD_Node\",job=\"kube-state-metrics\",status=\"true\",condition=~\"MemoryPressure|PIDPressure|DiskPressure|NetworkUnavailable\"} ",
       "legendFormat": "{{condition}}"
      }
     ]
    },
    {
     "title": "PoD ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (kubelet_running_pods{cluster=\"$Cluster\",instance=\"$PoD_Node\"})",
       "legendFormat": "Running "
      }
     ]
    },
    {
     "title": "Node CPU usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum (rate(node_cpu_seconds_total{cluster=\"$Cluster\",instance=\"$PoD_Node\"}[1h]))",
       "legendFormat": "usage"
      }
     ]
    },
    {
     "title": "Node Memory usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) - ((node_memory_MemFree_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Buffers_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}) + (node_memory_Cached_bytes{cluster=\"$Cluster\",instance=\"$PoD_Node\"}))",
       "legendFormat": "usage"
      },
      {
       "expr": "(node_memory_Buffers_bytes{instance=\"$PoD_Node\"})",
       "legendFormat": "buffers"
      },
      {
       "expr": "(node_memory_Cached_bytes{instance=\"$PoD_Node\"})",
       "legendFormat": "cached"
      },
      {
       "expr": "(node_memory_MemFree_bytes{instance=\"$PoD_Node\"})",
       "legendFormat": "free"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{instance=\"$PoD_Node\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Node load usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum(node_load1{cluster=\"$Cluster\",instance=\"$PoD_Node\"})",
       "legendFormat": "Load 1"
      },
      {
       "expr": "sum(node_load5{instance=\"$PoD_Node\"})",
       "legendFormat": "Load 5"
      },
      {
       "expr": "sum(node_load15{instance=\"$PoD_Node\"})",
       "legendFormat": "Load 15"
      }
     ]
    },
    {
     "title": "Node Disk usage",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_disk_read_bytes_total{cluster=\"$Cluster\",instance=\"$PoD_Node\"}[5m]))",
       "legendFormat": "Read"
      },
      {
       "expr": "sum(rate(node_disk_written_bytes_total{instance=\"$PoD_Node\"}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{instance=\"$PoD_Node\"}[5m])) ",
       "legendFormat": "IO time"
      }
     ]
    },
    {
     "title": "Node Network usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes", "label": "MB" }
     ],
     "targets": [
      {
       "expr": "sum (rate(node_network_transmit_bytes_total{cluster=\"$Cluster\",instance=\"$PoD_Node\"}[5m]))",
       "legendFormat": "node_out"
      },
      {
       "expr": "sum (rate (node_network_transmit_bytes_total{device=\"eth0\",instance=\"$PoD_Node\"}[5m]))",
       "legendFormat": "eth0 out"
      },
      {
       "expr": "sum (rate (node_network_transmit_bytes_total{device=\"eth1\",instance=\"$PoD_Node\"}[5m]))",
       "legendFormat": "eth1 out"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{pod=~\"$PoD\"}",
       "legendFormat": "current  "
      },
      {
       "expr": "jvm_threads_daemon{pod=~\"$PoD\"}",
       "legendFormat": "daemon "
      },
      {
       "expr": "jvm_threads_deadlocked {pod=~\"$PoD\"}",
       "legendFormat": "deadlock"
      },
      {
       "expr": "jvm_threads_deadlocked_monitor {pod=~\"$PoD\"}",
       "legendFormat": "deadlock monitor"
      }
     ]
    },
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{pod=~\"$PoD\"}",
       "legendFormat": "{{area}} memory "
      }
     ]
    },
    {
     "title": "GC time / 1 min. rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{instance=~\"$PoD\"}[1m])",
       "legendFormat": "{{gc}} "
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{pod=~\"$PoD\"}",
       "legendFormat": "{{gc}} "
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{pod=~\"$PoD\"}",
       "legendFormat": "loaded "
      }
     ]
    }
   ]
  },
  {
   "title": "MQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Messages in Queue",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages{instance=~\"$PoD\",queue!=\"\"}",
       "legendFormat": "Queue ( {{queue}} )"
      }
     ]
    }
   ]
  }
 ]
}