apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
  name: tempo-tempo-distributed
data:
  overrides.yaml: |
    overrides: {}
  tempo-query.yaml: |
    backend: 127.0.0.1:3100
  tempo.yaml: |
    multitenancy_enabled: false
    compactor:
      compaction:
        block_retention: 48h
      ring:
        kvstore:
          store: memberlist
    distributor:
      ring:
        kvstore:
          store: memberlist
      receivers:
    querier:
      frontend_worker:
        frontend_address: tempo-query-frontend-discovery:9095
    ingester:
      lifecycler:
        ring:
          replication_factor: 1
          kvstore:
            store: memberlist
        tokens_file_path: /var/tempo/tokens.json
    memberlist:
      abort_if_cluster_join_fails: false
      join_members:
        - tempo-gossip-ring
    overrides:
      per_tenant_override_config: /conf/overrides.yaml
    server:
      http_listen_port: 3100
    storage:
      trace:
        backend: s3
        s3:
          access_key: admin
          bucket: tracing
          endpoint: 172.31.14.138:9000
          insecure: true
          secret_key: admin2675
        blocklist_poll: 5m
        local:
          path: /var/tempo/traces
        wal:
          path: /var/tempo/wal
        cache: memcached
        memcached:
          consistent_hash: true
          host: tempo-memcached
          service: memcached-client
          timeout: 500ms

